name: form_test
description: "Test project for Forms."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

  flex_color_scheme: ^8.0.0
  flutter_form_builder: ^9.5.0
  flutter_hooks: ^0.20.5
  form_builder_validators: ^11.0.0
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  faker: ^2.2.0
  go_router: ^14.4.1
  go_router_builder: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints:
  riverpod_generator: ^2.6.2
  riverpod_lint: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
